version: "3.8"
services:
  app:
    build: .
    environment:
      APP_TRANSPORT_PORT: "[::]:5000"

      APP_REPOSITORY_USER: "postgres"
      APP_REPOSITORY_PASSWORD: "password"
      APP_REPOSITORY_HOST: "postgres"
      APP_REPOSITORY_DATABASE: "pgdb"
    ports:
      - "5000:5000"

  grpcox:
    image: gusaul/grpcox
    ports:
      - "6969:6969"

  tg-gateway:
    image: kuwerin/tg-gateway:latest
    env_file:
      - .env

  postgres:
      image: postgres:14.2
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
        POSTGRES_DB: pgdb
      volumes:
        - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
      ports:
        - "8081:5432"